Entity Framework Core/11.Best Practices and Architecture/PetStore/PetStore.Web/Models/Category/CreateCategoryInputModel.cs
namespace PetStore.Web.Models.Category
{
    using System.ComponentModel.DataAnnotations;
    
    public class CreateCategoryInputModel
    {
        [Required]
        [StringLength(50, MinimumLength = 3)]
        public string Name { get; set; }

        [StringLength(1000)]
        public string Description { get; set; }
    }
}

Entity Framework Core/11.Best Practices and Architecture/PetStore/PetStore.Web/Models/Category/EditCategoryViewModel.cs
namespace PetStore.Web.Models.Category
{
    using System.ComponentModel.DataAnnotations;

    public class EditCategoryViewModel
    {
        [Required]
        [StringLength(50, MinimumLength = 3)]
        public string Name { get; set; }

        [StringLength(1000)]
        public string Description { get; set; }
    }
}

Entity Framework Core/11.Best Practices and Architecture/PetStore/PetStore.Web/Models/ErrorViewModel.cs
using System;

namespace PetStore.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Entity Framework Core/11.Best Practices and Architecture/PetStore/PetStore.Web/Models/Pet/AllPetsViewModel.cs
namespace PetStore.Web.Models.Pet
{
    using System;
    using System.Collections.Generic;

    using Services.Models.Pet;

    public class AllPetsViewModel
    {
        public IEnumerable<PetListingServiceModel> Pets { get; set; }

        public int CurrentPage { get; set; }

        public int Total { get; set; }

        public int PreviosPage => this.CurrentPage - 1;

        public int NextPage => this.CurrentPage + 1;

        public bool PreviousDisabled => this.CurrentPage == 1;

        public bool NextDisabled 
        {
            get 
            {
                var maxPage = Math.Ceiling((double)this.Total / 25);

                return maxPage == this.CurrentPage;
            }
        }
    }
}

Entity Framework Core/11.Best Practices and Architecture/PetStore/PetStore.Web/Controllers/CategoriesController.cs
namespace PetStore.Web.Controllers
{
    using Services;
    using Services.Implementations;
    using Models.Category;
    using Microsoft.AspNetCore.Mvc;
    using Services.Models.Category;

    public class CategoriesController : Controller
    {
        private readonly ICategoryService categoryService;

        public CategoriesController(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }

        public IActionResult All() 
        {
            var allCategories = this.categoryService.All();

            return View(allCategories);
        }

        public IActionResult Create() 
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CreateCategoryInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.RedirectToAction("Error", "Home");
            }

            var serviceModel = new CategoryCreateServiceModel 
            {
                Name = model.Name,
                Description = model.Description
            };

            this.categoryService.Create(serviceModel);

            return this.RedirectToAction("All", "Categories");
        }

        public IActionResult Edit(int id) 
        {
            var category = this.categoryService.Details(id);

            return View(category);
        }

        [HttpPost]
        public IActionResult Edit(EditCategoryViewModel model) 
        {
            if (!this.ModelState.IsValid)
            {
                return RedirectToAction("Error", "Home");
            }

            var serviceModel = new CategoryEditServiceModel 
            {
                Name = model.Name,
                Description = model.Description
            };

            this.categoryService.Edit(serviceModel);

            return this.RedirectToAction("All", "Categories");
        }

        public IActionResult Details(int id)
        {
            var category = this.categoryService.Details(id);

            return View(category);
        }
    }
}

Entity Framework Core/11.Best Practices and Architecture/PetStore/PetStore.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PetStore.Web.Models;

namespace PetStore.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Entity Framework Core/11.Best Practices and Architecture/PetStore/PetStore.Web/Controllers/PetsController.cs
namespace PetStore.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Services;
    using Models.Pet;

    public class PetsController : Controller
    {
        private readonly IPetService petService;

        public PetsController(IPetService petService)
        {
            this.petService = petService;
        }

        public IActionResult All(int page = 1)
        {
            var allPets = this.petService.All(page);
            var total = this.petService.Total();

            var model = new AllPetsViewModel 
            {
                Pets = allPets,
                CurrentPage = page,
                Total = total
            };

            return View(model);
        }

        public IActionResult Delete(int id) 
        {
            var pet = this.petService.Details(id);

            if (pet == null)
            {
                return NotFound();
            }

            return View(pet);
        }

        public IActionResult ConfirmDelete(int id) 
        {
            var deleted = this.petService.Delete(id);

            if (!deleted)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(All));
        }
    }
}

Entity Framework Core/11.Best Practices and Architecture/PetStore/PetStore.Web/Views/Categories/All.cshtml
@model IEnumerable<PetStore.Services.Models.Category.CategoryListingServiceModel>

<h1>All Categories</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

Entity Framework Core/11.Best Practices and Architecture/PetStore/PetStore.Web/Views/Categories/Create.cshtml
@model PetStore.Data.Models.Category

<h1>Create Category</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="All">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Entity Framework Core/11.Best Practices and Architecture/PetStore/PetStore.Web/Views/Categories/Details.cshtml
@model PetStore.Services.Models.Category.CategoryDetailsServiceModel

<h1>Details</h1>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="All">Back to List</a>
</div>
@section Scripts {
    @Html.ActionLink("Details", "Details", new { id = Model.Id })
}

Entity Framework Core/11.Best Practices and Architecture/PetStore/PetStore.Web/Views/Categories/Edit.cshtml
@model CategoryDetailsServiceModel

<h1>Edit Category</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="/Edit/{id}">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" value="@Model.Name" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" value="@Model.Description" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="All">Back to List</a>
</div>

@section Scripts {
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id })
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Entity Framework Core/11.Best Practices and Architecture/PetStore/PetStore.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Entity Framework Core/11.Best Practices and Architecture/PetStore/PetStore.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]PetStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PetStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pets" asp-action="All">Pets</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="All">Categories</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - PetStore.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>